# spring.application.name=thymeleaf

# JDBC 설정 -> HikariCP(내장) -> DBCP 구축
# spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
# spring.datasource.url=jdbc:oracle:thin:@localhost:1521/xe
# spring.datasource.username=springboot
# spring.datasource.password=java1234

# # Mybatis 설정 -> 없음
# mybatis.mapper-locations=classpath:mapper/*.xml
# mybatis.type-aliases-package=com.test.thymeleaf.dto

spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    username: springboot
    url: jdbc:oracle:thin:@localhost:1521/xe
    password: java1234
  application:
    name: thymeleaf
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.test.thymeleaf.dto